### PR TITLE
Win filepath

### PR DESCRIPTION
**Pull request by fishfacegit**
I currently try to make this unpacker work on a Ubuntu Host with Win10 Guest.
It seems that pyinstaller has troubles with escaped paths '\\', creating a Errno 22 on open(...)
Therefore i changed most paths to `os.path.join([...])`, i think that's the proper way to do it.

### CODE REVIEW

**Comment by UrmelAusDemEis** [comment]
Hey! Thanks for the PR! However, I think that you can't use os.path.join() with a list. The strings you want to join have to be separate arguments. In most cases you added the star to unpack the list, however I think not in all cases :)

>>> import os
>>> os.path.join(["path1", "path2"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not list
>>> os.path.join("path1", "path2")
'path1/path2'

**Comment by UrmelAusDemEis** [comment]
I have made some cosmetic changes. Can you maybe test if it still works on your end? *cries in no tests*

**Comment by fishfacegit** [comment]
Hi Urmel,
This is my first PR.
Thank you for your help!

**Comment by UrmelAusDemEis** [comment]
Don't worry.
If you have changes, that aren't commited yet, you can pull with --rebase

**Comment by fishfacegit** [comment]
Worked for me!
image

**Comment by fishfacegit** [comment]
My setup was:
i set up a docker container, inside docker i run a qemu instance of win10.
Docker is basically the ubuntu host, and qemu the win10 sandbox/client.

**Comment by UrmelAusDemEis** [comment]
Awesome! Thank you for your contribution! :)

**Pull request merged**
